
services:

  db:
    image: postgres:16-alpine
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_USER: projektjava
      POSTGRES_PASSWORD: haslohaslo123
      POSTGRES_DB: projektjava_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"


volumes:
  postgres_data: