version: '3.8'
services:
  oracle19c:
    image: oracle/database:19.3.0-ee
    container_name: oracle19c
    ports:
      - "1521:1521"
    environment:
      - ORACLE_SID=orcl
      - ORACLE_PWD=OracleHomeUser1
    volumes:
      - ./oradata:/opt/oracle/oradata
      - ./baza_danych.sql:/container-entrypoint-initdb.d/baza_danych.sql
    restart: always
